# TODO: db: run service correctly
# TODO: db: setup non-root user/grants
# TODO: test: implement/actually run the test

version: '2'

services:
    db:
        image: ret1/v0001
        environment:
            MYSQL_ROOT_PASSWORD: example
            DJ_USER: root
            DJ_PASS: example
        ports:
          - '3306:3306'
        volumes:
          - ./data:/var/lib/mysql
          - ./crcns_ret-1:/data

